### ISSUE TITLE
Revisit sphinx-autoapi templates

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/ansys-sphinx-theme#354]
Ensure that:

- [x] Object name is not included in method or property description. Can only be fixed via CSS to ensure xref are still valid and unique. Implemented in #358. Example:

      ```
      FooObject.bar_property -> bar_property
      ```
      
- [x] Create "api" group in external dependencies. Implemented in #355 
- [x] Use Nerd Fonts for rendering symbols in toctree. Implemented in #362
- [x] Ensure typehints are using "short" qualification when rendering. Example:

      ```
      def function(foo: ansys.library.core.Foo) -> def function(foo: Foo)
      ```
      
     Default "sphinx-autoapi" templates for "method.rst" are using the [Sphinx Python Domain](https://www.sphinx-doc.org/en/master/usage/domains/python.html) to avoid enabling additional extensions. Consider using "autodoc" rather than `.. py:method::`.
     
     See `typehints_fully_qualified = False` from https://github.com/tox-dev/sphinx-autodoc-typehints
     See `autodoc_typehints_format = "short"` from https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html #358

**Comment by Revathyvenugopal162** [comment]
closing since All tasks have been completed.
